spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
        # ... (resto de tu config de base de datos)

    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
        # ...

    sql:
        init:
            mode: always

logging:
    level:
        root: warn
        org.springframework.jdbc.datasource.init: debug

# ESTO DEBE ESTAR AL RAS DEL MARGEN (Nivel raíz)
app:
    version: ${APP_VERSION:1.0.0-snapshot}