name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Debug - List files # Esto nos dirá en la consola dónde están los archivos
        run: ls -R

      - name: Grant execute permission
        # Este comando busca gradlew y le da permisos sin importar la carpeta
        run: find . -name "gradlew" -exec chmod +x {} +

      - name: Build with Gradle
        # Ejecutamos el build buscando el gradlew dinámicamente
        run: |
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          $GRADLEW_PATH clean build

      - name: Run Tests
        run: |
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          $GRADLEW_PATH test